PREFIX mmkg: <http://example.org/mmkg/schema/>
SELECT ?case ?organType ?tvol ?ovol (ROUND(1000*(?tvol/?ovol))/10 AS ?pct_of_organ)
WHERE { ?c a mmkg:ImagingCase ; mmkg:case_id ?case ; mmkg:depicts_organ ?o .
        ?o a ?organType ; mmkg:gt_volume_cm3 ?ovol .
        ?l mmkg:located_in ?o ; mmkg:gt_volume_cm3 ?tvol .
        FILTER(?organType != mmkg:Organ) }
ORDER BY DESC(?pct_of_organ) LIMIT 12
