#!/usr/bin/env python3
"""v12 hand-over: EVERY table cell from the de-duplicated-pool reruns (pool size derived from the corpus)
(results/retrieval/dedup/), formatted per draft table so Tables 8-10/C.19 can be re-transcribed
in one pass. -> docs/VKG_v12_dedup_table_cells_2026-09-17.md"""
import json
import os
import subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
D = os.path.join(ROOT, "results", "retrieval", "dedup")
OUT = os.path.join(ROOT, "docs", "VKG_v12_dedup_table_cells_2026-09-17.md")

t7 = json.load(open(f"{D}/retrieval_tab7_primary.json"))
t8 = json.load(open(f"{D}/retrieval_tab8_stress.json"))
t9 = json.load(open(f"{D}/retrieval_tab9_stratified.json"))
bl = json.load(open(f"{D}/baselines_tab7_tab8.json"))
ip = json.load(open(f"{D}/retrieval_iii_prime.json"))
c19 = json.load(open(f"{D}/tab10_example_ranks.json"))
sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, cwd=ROOT).stdout.strip()

L = []
def w(s=""):
    L.append(s)

def dcell(v):
    d = v.get("dmAP_vs_ii")
    if not isinstance(d, dict):
        return "—", "—"
    return f"{d['delta']:+.3f} [{d['ci95'][0]:.3f}, {d['ci95'][1]:.3f}]", str(d.get("p_holm"))

import json as _json
_nfl = len(_json.load(open(os.path.join(ROOT, "corpora", "corpus_flare23_kg_dedup.json")))["records"])
_npool = 113 + _nfl
_nsub = bl["tab8_subpool"]["n_candidates"]
_twins = 1312 - _nfl
w(f"# v12 hand-over — de-duplicated {_npool:,}-pool table cells (generated from `results/retrieval/dedup/` at `{sha}`)")
w()
w(f"Pool: **{_npool:,}** = 113 single-organ queries + {_nfl:,} FLARE23 ({_twins} query twins removed — 78 original "
  f"+ 13 by the 2026-09-20 axis-normalized census, `results/audit/axis_normalized_twin_census.json`; "
  f"`corpora/corpus_flare23_kg_dedup.json`). Baseline (v)–(vii′) cells: **{_nsub}-case CT sub-pool** "
  f"(113 + {_nsub - 113} dedup FLARE23 with a CT), per-query depth-30 re-rank validated against the frozen "
  "Delta 113-pool numbers (third-decimal reproduction, all eight configurations). "
  "Generated by `scripts/reports/make_v12_dedup_cells.py` — regenerate after any dedup rerun.")
w()

w("## Draft Table 8 — primary controlled benchmark (113-case pool, reference relevance)")
w()
w("| Configuration | P@5 | P@10 | mAP | nDCG | Spur.@10 | Mism.@10 | ΔmAP vs (ii) [95% CI] | p (Holm) |")
w("|:--|--:|--:|--:|--:|--:|--:|:--|:--|")
for k, v in bl["tab7"]["rows"].items():
    d, p = dcell(v)
    spur = "n/a" if k.startswith(("(v", "(vi", "(vii")) else v["spurious@10"]
    w(f"| {k} | {v['P@5']} | {v['P@10']} | {v['mAP']} | {v['nDCG']} | {spur} | {v['mismatch@10']} | {d} | {p} |")
v = ip["tab7_pool"]["(iii') imputed-absent"]
d, p = dcell(v)
w(f"| (iii′) imputed-absent (suppl.) | {v['P@5']} | {v['P@10']} | {v['mAP']} | {v['nDCG']} | {v['spurious@10']} | {v['mismatch@10']} | {d} | {p} |")
w()

w("*CANONICAL note (YL item 1, 09-18): row (vii) Δ = **−0.263 [−0.290, −0.237]** (this file / retrieval/dedup/) is the")
w("canonical value; the frozen Delta-run file reads −0.262 [−0.290, −0.236] — same mAP/P@10/nDCG and identical Holm p;")
w("the 0.001 is ResNet-embedding float nondeterminism across hardware at a rounding boundary (resampling is seeded and")
w("bit-identical). Spur.@10 reads **n/a** for baseline rows (v)–(vii′) per the caption (path-based, undefined for")
w("non-graph methods); the JSONs record the no-shared-organ rate under that key if a number is ever wanted.*")
w()
w(f"## Draft Table 9 — large-pool stress test ({_npool:,}-case de-duplicated pool)")
w()
w(f"### KG rows, full {_npool:,} pool")
w()
w("| Configuration | P@5 | P@10 | mAP | nDCG | Spur.@10 | Mism.@10 | ΔmAP vs (ii) [95% CI] | p (Holm) |")
w("|:--|--:|--:|--:|--:|--:|--:|:--|:--|")
for k, v in t8["rows"].items():
    d, p = dcell(v)
    w(f"| {k} | {v['P@5']} | {v['P@10']} | {v['mAP']} | {v['nDCG']} | {v['spurious@10']} | {v['mismatch@10']} | {d} | {p} |")
v = ip["tab8_pool_1425"]["(iii') imputed-absent"]
d, p = dcell(v)
w(f"| (iii′) imputed-absent (suppl.) | {v['P@5']} | {v['P@10']} | {v['mAP']} | {v['nDCG']} | {v['spurious@10']} | {v['mismatch@10']} | {d} | {p} |")
w()
w(f"### All rows, {_nsub}-case CT sub-pool (KG rows re-run for the like-for-like Δ)")
w()
w("| Configuration | P@5 | P@10 | mAP | nDCG | Spur.@10 | Mism.@10 | ΔmAP vs (ii) [95% CI] | p (Holm) |")
w("|:--|--:|--:|--:|--:|--:|--:|:--|:--|")
for k, v in bl["tab8_subpool"]["rows"].items():
    d, p = dcell(v)
    spur = "n/a" if k.startswith(("(v", "(vi", "(vii")) else v["spurious@10"]
    w(f"| {k} | {v['P@5']} | {v['P@10']} | {v['mAP']} | {v['nDCG']} | {spur} | {v['mismatch@10']} | {d} | {p} |")
w()

w("## Draft Table 10 — stratified retrieval (de-duplicated pool)")
w()
w("| Stratum | Method | n_q | P@5 | P@10 | mAP | nDCG | Mism.@10 | Δobs mAP [95% CI] | p (Holm) |")
w("|:--|:--|--:|--:|--:|--:|--:|--:|:--|:--|")
for key, v in t9["strata"].items():
    dd = v.get("delta_obs_mAP")
    if isinstance(dd, dict):
        dtxt, ptxt = f"{dd['delta']:+.3f} [{dd['ci95'][0]:.3f}, {dd['ci95'][1]:.3f}]", str(dd.get("p_holm"))
    else:
        dtxt, ptxt = "0.000 (exact tie)", "—"
    for m in ("proposed", "coverage_blind"):
        a = v[m]
        w(f"| {key if m == 'proposed' else ''} | {m} | {a['n_queries']} | {a['P@5']} | {a['P@10']} | "
          f"{a['mAP']} | {a['nDCG']} | {a.get('mismatch@10', 'n/a')} | {dtxt if m == 'proposed' else ''} | "
          f"{ptxt if m == 'proposed' else ''} |")
w()

w(f"### (iii′) rows for Table 10 (returned to the main table per YL 09-18; {_npool:,} pool)")
w()
w("| Stratum | n_q | P@5 | P@10 | mAP | nDCG | Mism.@10 | ΔmAP vs (ii) [95% CI] | p |")
w("|:--|--:|--:|--:|--:|--:|--:|:--|:--|")
K3 = "(iii') imputed-absent"
for ds in ("kits", "lits", "msd"):
    v = ip["tab9_a_within_dataset"][ds][K3]
    d, pp = dcell(v)
    w(f"| (a) within-dataset — {ds} | {v['n_queries']} | {v['P@5']} | {v['P@10']} | {v['mAP']} | {v['nDCG']} | {v['mismatch@10']} | {d} | {pp} |")
for key, lab in (("tab9_b_single_to_flare23", "(b) single-organ → FLARE23"),
                 ("tab9_c_flare23_to_single", "(c) FLARE23 → single-organ")):
    v = ip[key][K3]
    d, pp = dcell(v)
    w(f"| {lab} | {v['n_queries']} | {v['P@5']} | {v['P@10']} | {v['mAP']} | {v['nDCG']} | {v['mismatch@10'] if v['mismatch@10'] is not None else 'n/a'} | {d} | {pp} |")
w()

w("## Table C.19 — example query ranks (de-duplicated pool)")
w()
w("```json")
w(json.dumps({k: v for k, v in c19.items() if k != "definitions"}, indent=1)[:4000])
w("```")
w()
w("*(iii′) full columns both pools: `retrieval/dedup/retrieval_iii_prime.json`. Study set: "
  "`results/study/clinician_study_30q.json` (final, UNGRADED — grades/κ/nDCG@10/F5 pend recruitment).*")

open(OUT, "w").write("\n".join(L) + "\n")
print(f"-> {OUT} ({len(L)} lines)")
