#!/usr/bin/env python3
"""results/PROVENANCE.md — for every tracked results file: the script that writes it (found by grepping the
scripts for the file name), its inputs as documented in that script's docstring header, the last commit that
touched the file, and its date. Regenerate after any results change:  python scripts/reports/make_provenance.py
"""
import glob
import os
import re
import subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
os.chdir(ROOT)
scripts = {f: open(f).read() for f in glob.glob("scripts/**/*.py", recursive=True) + glob.glob("queries/*.py")}
rows = []
for f in sorted(subprocess.run(["git", "ls-files", "results"], capture_output=True, text=True).stdout.split()):
    if not f.endswith((".json", ".txt")):
        continue
    base = os.path.basename(f); stem = re.sub(r"(_qwen3_32b|_delta_repro|_naive_attribution)?\.(json|txt)$", "", base)
    # match literal names and f-string templates such as ausam_3d_{a.dataset}.json / tumor_incremental{TAG}.json
    tmpl = re.sub(r"_(flare_task2|flare23|flare|kits|lits|msd|pancreas)(?=\.|$)", "", stem)
    writers = [s for s, t in scripts.items() if base in t or (stem in t and "json.dump" in t)
               or re.search(re.escape(tmpl) + r"\{[^}]*\}", t) or re.search(re.escape(tmpl) + r"_\{[^}]*\}", t)]
    writers = sorted(set(writers), key=lambda s: (base not in scripts[s], s))[:2]
    log = subprocess.run(["git", "log", "-1", "--format=%h %ad", "--date=short", "--", f], capture_output=True, text=True).stdout.strip()
    rows.append((f, ", ".join(f"`{w}`" for w in writers) or "—", log))
out = ["# Provenance of results files", "", "Generated by `scripts/reports/make_provenance.py`. Script = the bundle script that writes the file",
       "(the v6 originals under `scripts/` with `/home/user/...` roots are the historical producers of the v6 files).",
       "`results/repair/flare_full_cases_40.txt` is the hand-reconstructed 40-patient list (first 40 FLARE23 release cases with a CT and all five",
       "KG organs + tumor labeled; see `docs/VKG_v8_closed_loop_findings_2026-09-13.md` §0).", "",
       "| File | Producing script(s) | Last commit (date) |", "|:--|:--|:--|"]
out += [f"| `{f}` | {w} | {log} |" for f, w, log in rows]
open("results/PROVENANCE.md", "w").write("\n".join(out) + "\n")
print(f"{len(rows)} files -> results/PROVENANCE.md")
